package service

import kotlinx.serialization.Serializable
import kotlinx.datetime.Instant

/**
 * Data models for SmartCompletionEngine.
 */

@Serializable
data class PhraseCompletion(
    val phrase: String,
    val displayText: String,
    val confidence: Double,
    val source: CompletionSource,
    val context: String? = null,
    val insertType: InsertType = InsertType.APPEND,
    val grammarHint: String? = null
)

enum class CompletionSource {
    USER_PATTERN,    // Learned from user's writing
    AI,              // Generated by Ollama
    CONTEXT,         // Based on previous sentences
    GRAMMAR,         // Grammar rule-based
    GRAMMAR_HINT,    // Case hint only
    COMMON           // Common phrase
}

enum class InsertType {
    APPEND,          // Add to end
    REPLACE_WORD,    // Replace current word
    INSERT_CURSOR    // Insert at cursor
}

data class PhrasePattern(
    val phrase: String,
    val context: String?,
    var frequency: Int = 1,
    val firstUsed: Instant,
    var lastUsed: Instant = firstUsed
)

@Serializable
data class AiCompletion(
    val phrase: String,
    val confidence: Double
)

data class LearningStats(
    val totalPatterns: Int,
    val totalUsages: Int,
    val topPatterns: List<String>,
    val commonStarters: List<String>
)
